[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
    default-src 'self'; 
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com; 
    style-src 'self' 'unsafe-inline'; 
    img-src 'self' data:; 
    connect-src 'self' https://identity.netlify.com; 
    font-src 'self' data:; 
    object-src 'none';
    base-uri 'self';
    form-action 'self';
    """
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/reports/lighthouse.html"
  [headers.values]
    Content-Security-Policy = """
    default-src 'self'; 
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com; 
    style-src 'self' 'unsafe-inline'; 
    img-src 'self' data:; 
    connect-src 'self' https://identity.netlify.com; 
    font-src 'self' data:; 
    object-src 'none';
    base-uri 'self';
    form-action 'self';
    """
