[[plugins]]
  package = "@netlify/plugin-lighthouse"
  package = "netlify-plugin-is-website-vulnerable"

  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

